type LangCustomPluralized = {
  one_value: string;
  few_value?: string;
  many_value?: string;
  other_value: string;
};
type LangCustomValue = string | LangCustomPluralized;
type LangCustomStrings = {[key: string]: LangCustomValue};
type LangCustom = {[langCode: string]: LangCustomStrings};

const langCustom: LangCustom = {
  'ru': {
    'ThemeVeryDark': 'Очень тёмная',
    'ThemeDuck': 'Утка',
    'ThemeGlass': 'Стекло',
    'ThemeGlassGray': 'Серое стекло',
    'PinnedChatsShort': 'Закреплённые',
    'FilterAllChatsShort': 'Все',
    'AboutTab.Title': 'О нас',
    'AboutTab.ProjectName': 'Название проекта',
    'AboutTab.Technology': 'На чём собран',
    'AboutTab.Version': 'Версия',
    'AboutTab.Status': 'Статус',
    'AboutTab.StatusPlaceholder': 'Временная заглушка',
    'AboutTab.SourceCode': 'Исходный код',
    'AboutTab.OpenGitHub': 'Открыть GitHub',
    'AboutTab.UniqueTech': 'Уникальная технология',
    'AboutTab.TechDescription': 'Мы используем уникальную технологию для обхода блокировок, которая обеспечивает стабильный доступ даже в условиях ограничений.',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'У вас осталось **%1$d** бесплатное транскрибирование на этой неделе.',
      few_value: 'У вас осталось **%1$d** бесплатных транскрибирования на этой неделе.',
      many_value: 'У вас осталось **%1$d** бесплатных транскрибирований на этой неделе.',
      other_value: 'У вас осталось **%1$d** бесплатных транскрибирований на этой неделе.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Это голосовое сообщение слишком длинное для транскрибирования.',
    'AudioAndVideoTranscription.FloodWait': 'Транскрибирование голосовых сообщений сейчас недоступно. Пожалуйста, попробуйте позже.',
    'Archive.Empty.Title': 'Архив пуст',
    'Archive.Empty.Subtitle': 'Чаты, которые вы архивируете, будут перемещены сюда.',
    'GhostMode.Title': 'Режим невидимки',
    'GhostMode.Subtitle': 'Скрывает ваш онлайн-статус, время последнего посещения и метки о прочтении. Читайте сообщения бесследно — никто не узнает, что вы были здесь.',
    'GhostMode.Warning': 'Отправка сообщения, звонок или реакция выдадут вас. Счётчики непрочитанного могут вернуться после следующей синхронизации.',
    'Proxy': 'Прокси',
    'Proxy.Enabled': 'Использовать прокси',
    'Proxy.Type': 'Тип подключения',
    'Proxy.Type.MTProto': 'MTProto-прокси',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Добавить прокси',
    'Proxy.Add.Button': 'Добавить',
    'Proxy.Import': 'Импорт',
    'Proxy.ImportLink': 'Ссылка на прокси (t.me/proxy?... или tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Секрет (необязательно)',
    'Proxy.Username': 'Логин',
    'Proxy.Password': 'Пароль',
    'Proxy.Servers': 'Сохранённые прокси',
    'Proxy.Browser.Note': 'В браузере маршрутизировать трафик может только MTProto-прокси. Записи SOCKS5 и HTTP сохраняются, но подключение остаётся прямым.'
  },
  'uk': {
    'PinnedChatsShort': 'Закріплені',
    'FilterAllChatsShort': 'Усі',
    'AboutTab.Title': 'Про нас',
    'AboutTab.ProjectName': 'Назва проєкту',
    'AboutTab.Technology': 'На чому зібрано',
    'AboutTab.Version': 'Версія',
    'AboutTab.Status': 'Статус',
    'AboutTab.StatusPlaceholder': 'Тимчасова заглушка',
    'AboutTab.SourceCode': 'Вихідний код',
    'AboutTab.OpenGitHub': 'Відкрити GitHub',
    'AboutTab.UniqueTech': 'Унікальна технологія',
    'AboutTab.TechDescription': 'Ми використовуємо унікальну технологію для обходу блокувань, яка забезпечує стабільний доступ навіть в умовах обмежень.',
    'ThemeVeryDark': 'Дуже темна',
    'ThemeDuck': 'Качка',
    'ThemeGlass': 'Скло',
    'ThemeGlassGray': 'Сіре скло',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'У вас залишилося **%1$d** безкоштовне транскрибування на цьому тижні.',
      few_value: 'У вас залишилося **%1$d** безкоштовні транскрибування на цьому тижні.',
      many_value: 'У вас залишилося **%1$d** безкоштовних транскрибувань на цьому тижні.',
      other_value: 'У вас залишилося **%1$d** безкоштовних транскрибувань на цьому тижні.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Це голосове повідомлення занадто довге для транскрибування.',
    'AudioAndVideoTranscription.FloodWait': 'Транскрибування голосових повідомлень зараз недоступне. Будь ласка, спробуйте пізніше.',
    'Archive.Empty.Title': 'Архів порожній',
    'Archive.Empty.Subtitle': 'Чати, які ви архівуєте, буде переміщено сюди.',
    'GhostMode.Title': 'Режим невидимки',
    'GhostMode.Subtitle': 'Приховує ваш онлайн-статус, час останнього відвідування та позначки про прочитання. Читайте повідомлення безслідно — ніхто не дізнається, що ви були тут.',
    'GhostMode.Warning': 'Відправлення повідомлення, дзвінок або реакція видадуть вас. Лічильники непрочитаного можуть повернутися після наступної синхронізації.',
    'Proxy': 'Проксі',
    'Proxy.Enabled': 'Використовувати проксі',
    'Proxy.Type': 'Тип підключення',
    'Proxy.Type.MTProto': 'MTProto-проксі',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Додати проксі',
    'Proxy.Add.Button': 'Додати',
    'Proxy.Import': 'Імпорт',
    'Proxy.ImportLink': 'Посилання на проксі (t.me/proxy?... або tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Секрет (необов\'язково)',
    'Proxy.Username': 'Логін',
    'Proxy.Password': 'Пароль',
    'Proxy.Servers': 'Збережені проксі',
    'Proxy.Browser.Note': 'У браузері маршрутизувати трафік може тільки MTProto-проксі. Записи SOCKS5 та HTTP зберігаються, але з\'єднання залишається прямим.'
  },
  'be': {
    'PinnedChatsShort': 'Замацаваныя',
    'FilterAllChatsShort': 'Усе',
    'AboutTab.Title': 'Пра нас',
    'AboutTab.ProjectName': 'Назва праекта',
    'AboutTab.Technology': 'На чым сабраны',
    'AboutTab.Version': 'Версія',
    'AboutTab.Status': 'Статус',
    'AboutTab.StatusPlaceholder': 'Часовая заглушка',
    'AboutTab.SourceCode': 'Зыходны код',
    'AboutTab.OpenGitHub': 'Адкрыць GitHub',
    'AboutTab.UniqueTech': 'Унікальная тэхналогія',
    'AboutTab.TechDescription': 'Мы выкарыстоўваем унікальную тэхналогію для абыходу блакіровак, якая забяспечвае стабільны доступ нават ва ўмовах абмежаванняў.',
    'ThemeVeryDark': 'Вельмі цёмная',
    'ThemeDuck': 'Качка',
    'ThemeGlass': 'Шкло',
    'ThemeGlassGray': 'Шэрае шкло',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'У вас засталося **%1$d** бясплатнае транскрыбаванне на гэтым тыдні.',
      few_value: 'У вас засталося **%1$d** бясплатныя транскрыбаванні на гэтым тыдні.',
      many_value: 'У вас засталося **%1$d** бясплатных транскрыбаванняў на гэтым тыдні.',
      other_value: 'У вас засталося **%1$d** бясплатных транскрыбаванняў на гэтым тыдні.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Гэта галасавое паведамленне занадта доўгае для транскрыбавання.',
    'AudioAndVideoTranscription.FloodWait': 'Транскрыбаванне галасавых паведамленняў зараз недаступнае. Калі ласка, паспрабуйце пазней.',
    'Archive.Empty.Title': 'Архіў пусты',
    'Archive.Empty.Subtitle': 'Чаты, якія вы архівуеце, будуць перанесены сюды.',
    'GhostMode.Title': 'Рэжым невідзімкі',
    'GhostMode.Subtitle': 'Хавае ваш анлайн-статус, час апошняга наведвання і адзнакі аб прачытанні. Чытайце паведамленні бясследна — ніхто не даведаецца, што вы былі тут.',
    'GhostMode.Warning': 'Адпраўка паведамлення, званок або рэакцыя выдадуць вас. Лічыльнікі непрачытанага могуць вярнуцца пасля наступнай сінхранізацыі.',
    'Proxy': 'Проксі',
    'Proxy.Enabled': 'Выкарыстоўваць проксі',
    'Proxy.Type': 'Тып падключэння',
    'Proxy.Type.MTProto': 'MTProto-проксі',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Дадаць проксі',
    'Proxy.Add.Button': 'Дадаць',
    'Proxy.Import': 'Імпарт',
    'Proxy.ImportLink': 'Спасылка на проксі (t.me/proxy?... або tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Сакрэт (неабавязкова)',
    'Proxy.Username': 'Лагін',
    'Proxy.Password': 'Пароль',
    'Proxy.Servers': 'Захаваныя проксі',
    'Proxy.Browser.Note': 'У браўзеры маршрутызаваць трафік можа толькі MTProto-проксі. Запісы SOCKS5 і HTTP захоўваюцца, але падключэнне застаецца прамым.'
  },
  'kk': {
    'PinnedChatsShort': 'Бекітілген',
    'FilterAllChatsShort': 'Бәрі',
    'AboutTab.Title': 'Біз туралы',
    'AboutTab.ProjectName': 'Жобаның атауы',
    'AboutTab.Technology': 'Негізінде жасалған',
    'AboutTab.Version': 'Нұсқа',
    'AboutTab.Status': 'Күй',
    'AboutTab.StatusPlaceholder': 'Уақытша заглушка',
    'AboutTab.SourceCode': 'Бастапқы код',
    'AboutTab.OpenGitHub': 'GitHub-ты ашу',
    'AboutTab.UniqueTech': 'Бірегей технология',
    'AboutTab.TechDescription': 'Біз блоктауларды айналып өту үшін бірегей технологияны қолданамыз, ол шектеулер жағдайында да тұрақты қолжетімділікті қамтамасыз етеді.',
    'ThemeVeryDark': 'Өте қараңғы',
    'ThemeDuck': 'Үйрек',
    'ThemeGlass': 'Шыны',
    'ThemeGlassGray': 'Сұр шыны',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Бұл аптада сізде **%1$d** тегін транскрипция қалды.',
      other_value: 'Бұл аптада сізде **%1$d** тегін транскрипция қалды.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Бұл дауыстық хабарлама транскрипциялау үшін тым ұзақ.',
    'AudioAndVideoTranscription.FloodWait': 'Дауыстық хабарламаларды транскрипциялау қазір қолжетімсіз. Кейінірек қайталап көріңіз.',
    'Archive.Empty.Title': 'Мұрағат бос',
    'Archive.Empty.Subtitle': 'Сіз мұрағаттайтын чаттар осында жылжытылады.',
    'GhostMode.Title': 'Көрінбес режим',
    'GhostMode.Subtitle': 'Онлайн статусыңызды, соңғы кіру уақытыңызды және оқылған белгілерін жасырады. Хабарламаларды ізсіз оқыңыз — ешкім мұнда болғаныңызды білмейді.',
    'GhostMode.Warning': 'Хабарлама жіберу, қоңырау немесе реакция сізді ашады. Оқылмаған санауыштар келесі синхрондаудан кейін қайта пайда болуы мүмкін.',
    'Proxy': 'Прокси',
    'Proxy.Enabled': 'Проксиді пайдалану',
    'Proxy.Type': 'Қосылу түрі',
    'Proxy.Type.MTProto': 'MTProto прокси',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Прокси қосу',
    'Proxy.Add.Button': 'Қосу',
    'Proxy.Import': 'Импорт',
    'Proxy.ImportLink': 'Прокси сілтемесі (t.me/proxy?... немесе tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Құпия (міндетті емес)',
    'Proxy.Username': 'Пайдаланушы аты',
    'Proxy.Password': 'Құпиясөз',
    'Proxy.Servers': 'Сақталған прокси',
    'Proxy.Browser.Note': 'Браузерде трафикті тек MTProto прокси бағыттай алады. SOCKS5 және HTTP жазбалары сақталады, бірақ қосылу тікелей қалады.'
  },
  'uz': {
    'PinnedChatsShort': 'Mahkamlangan',
    'FilterAllChatsShort': 'Barchasi',
    'AboutTab.Title': 'Biz haqimizda',
    'AboutTab.ProjectName': 'Loyiha nomi',
    'AboutTab.Technology': 'Nimaga asoslangan',
    'AboutTab.Version': 'Versiya',
    'AboutTab.Status': 'Holat',
    'AboutTab.StatusPlaceholder': 'Vaqtinchalik stublar',
    'AboutTab.SourceCode': 'Manba kodi',
    'AboutTab.OpenGitHub': 'GitHub-ni ochish',
    'AboutTab.UniqueTech': 'Noyob texnologiya',
    'AboutTab.TechDescription': 'Biz blokirovkalarni chetlab o\'tish uchun noyob texnologiyadan foydalanamiz, bu cheklovlar sharoitida ham barqaror kirishni ta\'minlaydi.',
    'ThemeVeryDark': 'Juda qorong\'i',
    'ThemeDuck': 'O\'rdak',
    'ThemeGlass': 'Shisha',
    'ThemeGlassGray': 'Kulrang shisha',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Bu haftada sizda **%1$d** bepul transkripsiya qoldi.',
      other_value: 'Bu haftada sizda **%1$d** bepul transkripsiya qoldi.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Bu ovozli xabar transkripsiya qilish uchun juda uzun.',
    'AudioAndVideoTranscription.FloodWait': 'Ovozli xabarlarni transkripsiya qilish hozirda mavjud emas. Iltimos, keyinroq urinib ko\'ring.',
    'Archive.Empty.Title': 'Arxiv bo\'sh',
    'Archive.Empty.Subtitle': 'Siz arxivlaydigan chatlar shu yerga ko\'chiriladi.',
    'GhostMode.Title': 'Ko\'rinmas rejim',
    'GhostMode.Subtitle': 'Onlayn holatingizni, oxirgi tashrif vaqtingizni va o\'qilgan belgilarini yashiradi. Xabarlarni izsiz o\'qing — hech kim bu yerda bo\'lganingizni bilmaydi.',
    'GhostMode.Warning': 'Xabar yuborish, qo\'ng\'iroq yoki reaksiya sizni oshkor qiladi. O\'qilmagan hisoblagichlar keyingi sinxronlashdan keyin qaytishi mumkin.',
    'Proxy': 'Прокси',
    'Proxy.Enabled': 'Proksi-serverdan foydalanish',
    'Proxy.Type': 'Ulanish turi',
    'Proxy.Type.MTProto': 'MTProto proksi',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Proksi qo\'shish',
    'Proxy.Add.Button': 'Qo\'shish',
    'Proxy.Import': 'Import',
    'Proxy.ImportLink': 'Proksi havolasi (t.me/proxy?... yoki tg://proxy?...)',
    'Proxy.Server': 'Server',
    'Proxy.Port': 'Port',
    'Proxy.Secret': 'Maxfiy (ixtiyoriy)',
    'Proxy.Username': 'Foydalanuvchi nomi',
    'Proxy.Password': 'Parol',
    'Proxy.Servers': 'Saqlangan proksi',
    'Proxy.Browser.Note': 'Brauzerda faqat MTProto proksi trafikni yo\'naltira oladi. SOCKS5 va HTTP yozuvlari saqlanadi, lekin ulanish to\'g\'ridan-to\'g\'ri qoladi.'
  },
  'az': {
    'PinnedChatsShort': 'Sabitlənmiş',
    'FilterAllChatsShort': 'Hamısı',
    'AboutTab.Title': 'Bizim haqqımızda',
    'AboutTab.ProjectName': 'Layihənin adı',
    'AboutTab.Technology': 'Nə üzərində qurulub',
    'AboutTab.Version': 'Versiya',
    'AboutTab.Status': 'Status',
    'AboutTab.StatusPlaceholder': 'Müvəqqəti stublar',
    'AboutTab.SourceCode': 'Mənbə kodu',
    'AboutTab.OpenGitHub': 'GitHub-ı aç',
    'AboutTab.UniqueTech': 'Unikal texnologiya',
    'AboutTab.TechDescription': 'Bloklamaları keçmək üçün unikal texnologiyadan istifadə edirik; o, məhdudiyyət şəraitində belə stabil girişi təmin edir.',
    'ThemeVeryDark': 'Çox tünd',
    'ThemeDuck': 'Ördək',
    'ThemeGlass': 'Şüşə',
    'ThemeGlassGray': 'Boz şüşə',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Bu həftə sizdə **%1$d** pulsuz transkripsiya qalıb.',
      other_value: 'Bu həftə sizdə **%1$d** pulsuz transkripsiya qalıb.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Bu səsli mesaj transkripsiya üçün çox uzundur.',
    'AudioAndVideoTranscription.FloodWait': 'Səsli mesajların transkripsiyası hazırda mövcud deyil. Zəhmət olmasa, daha sonra yenidən cəhd edin.',
    'Archive.Empty.Title': 'Arxiv boşdur',
    'Archive.Empty.Subtitle': 'Arxivlədiyiniz söhbətlər buraya köçürüləcək.',
    'GhostMode.Title': 'Görünməz rejim',
    'GhostMode.Subtitle': 'Onlayn statusunuzu, son görülmə vaxtınızı və oxunma nişanlarını gizlədir. Mesajları izsiz oxuyun — heç kim burada olduğunuzu bilməyəcək.',
    'GhostMode.Warning': 'Mesaj göndərmək, zəng və ya reaksiya sizi ifşa edər. Oxunmamış sayğaclar növbəti sinxronizasiyadan sonra geri qayıda bilər.',
    'Proxy': 'Proksi',
    'Proxy.Enabled': 'Proksidən istifadə et',
    'Proxy.Type': 'Qoşulma növü',
    'Proxy.Type.MTProto': 'MTProto proksi',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Proksi əlavə et',
    'Proxy.Add.Button': 'Əlavə et',
    'Proxy.Import': 'İdxal',
    'Proxy.ImportLink': 'Proksi linki (t.me/proxy?... və ya tg://proxy?...)',
    'Proxy.Server': 'Server',
    'Proxy.Port': 'Port',
    'Proxy.Secret': 'Gizli (istəyə bağlı)',
    'Proxy.Username': 'İstifadəçi adı',
    'Proxy.Password': 'Şifrə',
    'Proxy.Servers': 'Saxlanılan proksi',
    'Proxy.Browser.Note': 'Brauzerdə trafiki yalnız MTProto proksi marşrutlaşdıra bilər. SOCKS5 və HTTP qeydləri saxlanılır, lakin qoşulma birbaşa qalır.'
  },
  'hy': {
    'PinnedChatsShort': 'Ամրացված',
    'FilterAllChatsShort': 'Բոլորը',
    'AboutTab.Title': 'Մեր մասին',
    'AboutTab.ProjectName': 'Նախագծի անվանումը',
    'AboutTab.Technology': 'Ինչի վրա է ստեղծված',
    'AboutTab.Version': 'Տարբերակ',
    'AboutTab.Status': 'Կարգավիճակ',
    'AboutTab.StatusPlaceholder': 'Ժամանակավոր փակող',
    'AboutTab.SourceCode': 'Աղբյուրի կոդ',
    'AboutTab.OpenGitHub': 'Բացել GitHub-ը',
    'AboutTab.UniqueTech': 'Եզակի տեխնոլոգիա',
    'AboutTab.TechDescription': 'Մենք օգտագործում ենք եզակի տեխնոլոգիա՝ արգելափակումները շրջանցելու համար, որն ապահովում է կայուն հասանելիություն նույնիսկ սահմանափակումների պայմաններում:',
    'ThemeVeryDark': 'Շատ մուգ',
    'ThemeDuck': 'Բադ',
    'ThemeGlass': 'Ապակի',
    'ThemeGlassGray': 'Մոխրագույն ապակի',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Այս շաբաթ ձեզ մոտ մնացել է **%1$d** անվճար տառադարձում։',
      other_value: 'Այս շաբաթ ձեզ մոտ մնացել է **%1$d** անվճար տառադարձում։'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Այս ձայնային հաղորդագրությունը չափազանց երկար է տառադարձելու համար։',
    'AudioAndVideoTranscription.FloodWait': 'Ձայնային հաղորդագրությունների տառադարձումը ներկայումս հասանելի չէ։ Խնդրում ենք փորձել ավելի ուշ։',
    'Archive.Empty.Title': 'Արխիվը դատարկ է',
    'Archive.Empty.Subtitle': 'Ձեր արխիվացված զրույցները կտեղափոխվեն այստեղ։',
    'GhostMode.Title': 'Անտեսանելի ռեժիմ',
    'GhostMode.Subtitle': 'Թաքցնում է ձեր առցանց կարգավիճակը, վերջին այցելության ժամանակը և կարդացվածության նշանները։ Կարդացեք հաղորդագրություններն անհետևանք — ոչ ոք չի իմանա, որ դուք այստեղ էիք։',
    'GhostMode.Warning': 'Հաղորդագրություն ուղարկելը, զանգը կամ ռեակցիան կբացահայտեն ձեզ։ Չկարդացված հաշվիչները կարող են վերադառնալ հաջորդ համաժամեցումից հետո։',
    'Proxy': 'Պրոքսի',
    'Proxy.Enabled': 'Օգտագործել պրոքսի',
    'Proxy.Type': 'Միացման տեսակ',
    'Proxy.Type.MTProto': 'MTProto պրոքսի',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Ավելացնել պրոքսի',
    'Proxy.Add.Button': 'Ավելացնել',
    'Proxy.Import': 'Ներմուծել',
    'Proxy.ImportLink': 'Պրոքսիի հղում (t.me/proxy?... կամ tg://proxy?...)',
    'Proxy.Server': 'Սերվեր',
    'Proxy.Port': 'Պորտ',
    'Proxy.Secret': 'Գաղտնիք (պարտադիր չէ)',
    'Proxy.Username': 'Օգտանուն',
    'Proxy.Password': 'Գաղտնաբառ',
    'Proxy.Servers': 'Պահված պրոքսի',
    'Proxy.Browser.Note': 'Բրաուզերում երթուղղել տրաֆիկը կարող է միայն MTProto պրոքսին։ SOCKS5 և HTTP գրառումները պահպանվում են, բայց կապը մնում է ուղիղ։'
  },
  'ka': {
    'PinnedChatsShort': 'მიმაგრებული',
    'FilterAllChatsShort': 'ყველა',
    'AboutTab.Title': 'ჩვენ შესახებ',
    'AboutTab.ProjectName': 'პროექტის სახელი',
    'AboutTab.Technology': 'რაზეა აგებული',
    'AboutTab.Version': 'ვერსია',
    'AboutTab.Status': 'სტატუსი',
    'AboutTab.StatusPlaceholder': 'დროებითი ჩამრთველი',
    'AboutTab.SourceCode': 'წყაროს კოდი',
    'AboutTab.OpenGitHub': 'GitHub-ის გახსნა',
    'AboutTab.UniqueTech': 'უნიკალური ტექნოლოგია',
    'AboutTab.TechDescription': 'ჩვენ ვიყენებთ უნიკალურ ტექნოლოგიას ბლოკირებების გვერდის ასავლელად, რომელიც უზრუნველყოფს სტაბილურ წვდომას შეზღუდვების პირობებშიც კი:',
    'ThemeVeryDark': 'ძალიან მუქი',
    'ThemeDuck': 'იხვი',
    'ThemeGlass': 'მინა',
    'ThemeGlassGray': 'ნაცრისფერი მინა',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'ამ კვირაში თქვენ გაქვთ **%1$d** უფასო ტრანსკრიფცია.',
      other_value: 'ამ კვირაში თქვენ გაქვთ **%1$d** უფასო ტრანსკრიფცია.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'ეს ხმოვანი შეტყობინება ძალიან გრძელია ტრანსკრიფციისთვის.',
    'AudioAndVideoTranscription.FloodWait': 'ხმოვანი შეტყობინებების ტრანსკრიფცია ამჟამად მიუწვდომელია. გთხოვთ, სცადოთ მოგვიანებით.',
    'Archive.Empty.Title': 'არქივი ცარიელია',
    'Archive.Empty.Subtitle': 'არქივირებული ჩატები აქ გადავა.',
    'GhostMode.Title': 'უხილავი რეჟიმი',
    'GhostMode.Subtitle': 'მალავს თქვენს ონლაინ სტატუსს, ბოლო ნახვის დროს და წაკითხვის ნიშნებს. წაიკითხეთ შეტყობინებები უკვალოდ — არავინ გაიგებს, რომ აქ იყავით.',
    'GhostMode.Warning': 'შეტყობინების გაგზავნა, ზარი ან რეაქცია გაგიმხელთ. წაუკითხავების მრიცხველები შეიძლება დაბრუნდეს შემდეგი სინქრონიზაციის შემდეგ.',
    'Proxy': 'პროქსი',
    'Proxy.Enabled': 'პროქსის გამოყენება',
    'Proxy.Type': 'კავშირის ტიპი',
    'Proxy.Type.MTProto': 'MTProto პროქსი',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'პროქსის დამატება',
    'Proxy.Add.Button': 'დამატება',
    'Proxy.Import': 'იმპორტი',
    'Proxy.ImportLink': 'პროქსის ბმული (t.me/proxy?... ან tg://proxy?...)',
    'Proxy.Server': 'სერვერი',
    'Proxy.Port': 'პორტი',
    'Proxy.Secret': 'საიდუმლო (არასავალდებულო)',
    'Proxy.Username': 'მომხმარებლის სახელი',
    'Proxy.Password': 'პაროლი',
    'Proxy.Servers': 'შენახული პროქსი',
    'Proxy.Browser.Note': 'ბრაუზერში ტრაფიკის მარშრუტიზება მხოლოდ MTProto პროქსის შეუძლია. SOCKS5 და HTTP ჩანაწერები ინახება, მაგრამ კავშირი პირდაპირი რჩება.'
  },
  'ky': {
    'PinnedChatsShort': 'Бекитилген',
    'FilterAllChatsShort': 'Баары',
    'AboutTab.Title': 'Биз жөнүндө',
    'AboutTab.ProjectName': 'Долбоордун аталышы',
    'AboutTab.Technology': 'Эмненин негизинде түзүлгөн',
    'AboutTab.Version': 'Версия',
    'AboutTab.Status': 'Статус',
    'AboutTab.StatusPlaceholder': 'Убактылуу кедерги',
    'AboutTab.SourceCode': 'Баштапкы код',
    'AboutTab.OpenGitHub': 'GitHub-ты ачуу',
    'AboutTab.UniqueTech': 'Уникалдуу технология',
    'AboutTab.TechDescription': 'Блокировкаларды айланып өтүү үчүн уникалдуу технологияны колдонобуз, ал чектөөлөрдүн шартында да туруктуу кирүүнү камсыздайт.',
    'ThemeVeryDark': 'Өтө караңгы',
    'ThemeDuck': 'Өрдөк',
    'ThemeGlass': 'Айнек',
    'ThemeGlassGray': 'Боз айнек',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Бул жумада сизде **%1$d** акысыз транскрипция калды.',
      other_value: 'Бул жумада сизде **%1$d** акысыз транскрипция калды.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Бул үн билдирүү транскрипция үчүн өтө узун.',
    'AudioAndVideoTranscription.FloodWait': 'Үн билдирүүлөрдү транскрипциялоо азырынча жеткиликтүү эмес. Сураныч, кийинчерээк кайра аракет кылыңыз.',
    'Archive.Empty.Title': 'Архив бош',
    'Archive.Empty.Subtitle': 'Сиз архивдеген чаттар ушул жакка жылдырылат.',
    'GhostMode.Title': 'Көрүнбөс режим',
    'GhostMode.Subtitle': 'Онлайн статусуңузду, акыркы кирүү убактыңызды жана окулган белгилерин жашырат. Билдирүүлөрдү изсиз окуңуз — эч ким бул жерде болгонуңузду билбейт.',
    'GhostMode.Warning': 'Билдирүү жөнөтүү, чалыш же реакция сизди ачып коёт. Окулбаган эсептегичтер кийинки синхрондоодон кийин кайтып келиши мүмкүн.',
    'Proxy': 'Прокси',
    'Proxy.Enabled': 'Прокси колдонуу',
    'Proxy.Type': 'Туташуу түрү',
    'Proxy.Type.MTProto': 'MTProto прокси',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Прокси кошуу',
    'Proxy.Add.Button': 'Кошуу',
    'Proxy.Import': 'Импорт',
    'Proxy.ImportLink': 'Прокси шилтемеси (t.me/proxy?... же tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Сыр (милдеттүү эмес)',
    'Proxy.Username': 'Колдонуучу аты',
    'Proxy.Password': 'Сырсөз',
    'Proxy.Servers': 'Сакталган прокси',
    'Proxy.Browser.Note': 'Браузерде трафикти багыттай турган бир гана MTProto прокси. SOCKS5 жана HTTP жазуулары сакталат, бирок туташуу түз бойдон калат.'
  },
  'tg': {
    'PinnedChatsShort': 'Сабтшуда',
    'FilterAllChatsShort': 'Ҳама',
    'AboutTab.Title': 'Дар бораи мо',
    'AboutTab.ProjectName': 'Номи лоиҳа',
    'AboutTab.Technology': 'Дар асоси чӣ сохта шудааст',
    'AboutTab.Version': 'Версия',
    'AboutTab.Status': 'Мақом',
    'AboutTab.StatusPlaceholder': 'Монеаи муваққатӣ',
    'AboutTab.SourceCode': 'Коди манбаъ',
    'AboutTab.OpenGitHub': 'Кушодани GitHub',
    'AboutTab.UniqueTech': 'Технологияи беназир',
    'AboutTab.TechDescription': 'Мо барои гузаштан аз монеаҳо технологияи беназирро истифода мебарем, ки дастрасии устуворро ҳатто дар шароити маҳдудиятҳо таъмин мекунад.',
    'ThemeVeryDark': 'Хеле торик',
    'ThemeDuck': 'Мурғобӣ',
    'ThemeGlass': 'Шиша',
    'ThemeGlassGray': 'Шишаи хокистарӣ',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Дар ин ҳафта ба шумо **%1$d** транскрипсияи ройгон монд.',
      other_value: 'Дар ин ҳафта ба шумо **%1$d** транскрипсияи ройгон монд.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Ин паёми овозӣ барои транскрипсия хеле дароз аст.',
    'AudioAndVideoTranscription.FloodWait': 'Транскрипсияи паёмҳои овозӣ ҳоло дастрас нест. Лутфан, дертар кӯшиш кунед.',
    'Archive.Empty.Title': 'Архив холӣ аст',
    'Archive.Empty.Subtitle': 'Чатҳое, ки шумо архив мекунед, ба ин ҷо интиқол дода мешаванд.',
    'GhostMode.Title': 'Реҷаи ноаён',
    'GhostMode.Subtitle': 'Ҳолати онлайни шумо, вақти охирин ташриф ва аломатҳои хондашударо пинҳон мекунад. Паёмҳоро беосар хонед — ҳеҷ кас намедонад, ки шумо дар ин ҷо будед.',
    'GhostMode.Warning': 'Фиристодани паём, занг ё реаксия шуморо фош мекунад. Ҳисоблагичҳои нохонда пас аз синхронизатсияи навбатӣ баргарданд.',
    'Proxy': 'Прокси',
    'Proxy.Enabled': 'Истифодаи прокси',
    'Proxy.Type': 'Намуди пайвастшавӣ',
    'Proxy.Type.MTProto': 'Прокси MTProto',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Илова кардани прокси',
    'Proxy.Add.Button': 'Илова',
    'Proxy.Import': 'Импорт',
    'Proxy.ImportLink': 'Пайванди прокси (t.me/proxy?... ё tg://proxy?...)',
    'Proxy.Server': 'Сервер',
    'Proxy.Port': 'Порт',
    'Proxy.Secret': 'Махфӣ (ихтиёрӣ)',
    'Proxy.Username': 'Номи корбар',
    'Proxy.Password': 'Парол',
    'Proxy.Servers': 'Проксиҳои нигоҳдошта',
    'Proxy.Browser.Note': 'Дар браузер танҳо прокси MTProto метавонад трафикро самт диҳад. Сабтҳои SOCKS5 ва HTTP нигоҳ дошта мешаванд, аммо пайвастшавӣ мустақим боқӣ мемонад.'
  },
  'tk': {
    'PinnedChatsShort': 'Berkitilen',
    'FilterAllChatsShort': 'Hemmesi',
    'AboutTab.Title': 'Biz barada',
    'AboutTab.ProjectName': 'Taslamanyň ady',
    'AboutTab.Technology': 'Näme esaslarynda guruldy',
    'AboutTab.Version': 'Wersiýa',
    'AboutTab.Status': 'Status',
    'AboutTab.StatusPlaceholder': 'Wagtlaýyn bloklama',
    'AboutTab.SourceCode': 'Çeşme kody',
    'AboutTab.OpenGitHub': 'GitHub-y açmak',
    'AboutTab.UniqueTech': 'Aýratyn tehnologiýa',
    'AboutTab.TechDescription': 'Bloklamalary aýlanyp geçmek üçin aýratyn tehnologiýany ulanýarys; ol çäklilikler şertinde-de durnukly girişi üpjün edýär.',
    'ThemeVeryDark': 'Örän garaňky',
    'ThemeDuck': 'Ördek',
    'ThemeGlass': 'Aýna',
    'ThemeGlassGray': 'Çöl aýna',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Bu hepdä sizde **%1$d** mugt transkripsiýa galdy.',
      other_value: 'Bu hepdä sizde **%1$d** mugt transkripsiýa galdy.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Bu sesli habar transkripsiýa üçin gaty uzyn.',
    'AudioAndVideoTranscription.FloodWait': 'Sesli habarlary transkripsiýa etmek häzirçe elýeterli däl. Haýyş, soňra täzeden synanyşyň.',
    'Archive.Empty.Title': 'Arhiw boş',
    'Archive.Empty.Subtitle': 'Arhiwlän söhbetleriňiz şu ýere geçiriler.',
    'GhostMode.Title': 'Görünmeýän rejim',
    'GhostMode.Subtitle': 'Onlaýn statusyňyzy, soňky wagt we okalan belgilerini gizleýär. Habarlary yzsyz okaň — hiç kim bu ýerde bolanyňyzy bilmez.',
    'GhostMode.Warning': 'Habar ibermek, jaň ýa-da reaksiýa sizi ýüze çykarar. Okalmadyk hasaplaýjylar indiki sinhronizasiýadan soň yza gaýdyp biler.',
    'Proxy': 'Proksi',
    'Proxy.Enabled': 'Proksi ulanmak',
    'Proxy.Type': 'Birikme görnüşi',
    'Proxy.Type.MTProto': 'MTProto proksi',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Proksi goşmak',
    'Proxy.Add.Button': 'Goş',
    'Proxy.Import': 'Import',
    'Proxy.ImportLink': 'Proksi baglanyşygy (t.me/proxy?... ýa-da tg://proxy?...)',
    'Proxy.Server': 'Serwer',
    'Proxy.Port': 'Port',
    'Proxy.Secret': 'Gizlin (hökman däl)',
    'Proxy.Username': 'Ulanyjy ady',
    'Proxy.Password': 'Açar sözi',
    'Proxy.Servers': 'Saklanýan proksi',
    'Proxy.Browser.Note': 'Brauzerde trafiki diňe MTProto proksi ugrukdyryp biler. SOCKS5 we HTTP ýazgylary saklanýar, ýöne birikme göni galýar.'
  },
  'ro': {
    'PinnedChatsShort': 'Fixate',
    'FilterAllChatsShort': 'Toate',
    'AboutTab.Title': 'Despre noi',
    'AboutTab.ProjectName': 'Numele proiectului',
    'AboutTab.Technology': 'Pe ce este construit',
    'AboutTab.Version': 'Versiune',
    'AboutTab.Status': 'Status',
    'AboutTab.StatusPlaceholder': 'Piesă temporară',
    'AboutTab.SourceCode': 'Cod sursă',
    'AboutTab.OpenGitHub': 'Deschideți GitHub',
    'AboutTab.UniqueTech': 'Tehnologie unică',
    'AboutTab.TechDescription': 'Folosim o tehnologie unică pentru a ocoli blocajele, care asigură un acces stabil chiar și în condiții de restricții.',
    'ThemeVeryDark': 'Foarte întunecat',
    'ThemeDuck': 'Rață',
    'ThemeGlass': 'Sticlă',
    'ThemeGlassGray': 'Sticlă gri',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Săptămâna aceasta mai aveți **%1$d** transcriere gratuită.',
      few_value: 'Săptămâna aceasta mai aveți **%1$d** transcrieri gratuite.',
      other_value: 'Săptămâna aceasta mai aveți **%1$d** de transcrieri gratuite.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Acest mesaj vocal este prea lung pentru a fi transcris.',
    'AudioAndVideoTranscription.FloodWait': 'Transcrierea mesajelor vocale nu este disponibilă momentan. Vă rugăm să încercați din nou mai târziu.',
    'Archive.Empty.Title': 'Arhiva este goală',
    'Archive.Empty.Subtitle': 'Conversațiile pe care le arhivați vor fi mutate aici.',
    'GhostMode.Title': 'Mod invizibil',
    'GhostMode.Subtitle': 'Ascunde statutul tău online, ora ultimei vizite și confirmările de citire. Citiți mesajele fără urmă — nimeni nu va ști că ați fost aici.',
    'GhostMode.Warning': 'Trimiterea unui mesaj, un apel sau o reacție vă va dezvălui. Contoarele necitite pot reveni după următoarea sincronizare.',
    'Proxy': 'Proxy',
    'Proxy.Enabled': 'Utilizează proxy',
    'Proxy.Type': 'Tipul conexiunii',
    'Proxy.Type.MTProto': 'Proxy MTProto',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Adaugă proxy',
    'Proxy.Add.Button': 'Adaugă',
    'Proxy.Import': 'Importă',
    'Proxy.ImportLink': 'Link proxyd (t.me/proxy?... sau tg://proxy?...)',
    'Proxy.Server': 'Server',
    'Proxy.Port': 'Port',
    'Proxy.Secret': 'Secret (opțional)',
    'Proxy.Username': 'Nume utilizator',
    'Proxy.Password': 'Parolă',
    'Proxy.Servers': 'Proxy-uri salvate',
    'Proxy.Browser.Note': 'În browser, doar un proxy MTProto poate direcționa traficul. Înregistrările SOCKS5 și HTTP sunt salvate, dar conexiunea rămâne directă.'
  },
  'lt': {
    'PinnedChatsShort': 'Prisegtieji',
    'FilterAllChatsShort': 'Visi',
    'AboutTab.Title': 'Apie mus',
    'AboutTab.ProjectName': 'Projekto pavadinimas',
    'AboutTab.Technology': 'Kuo pagrįstas',
    'AboutTab.Version': 'Versija',
    'AboutTab.Status': 'Būsena',
    'AboutTab.StatusPlaceholder': 'Laikinas kamštis',
    'AboutTab.SourceCode': 'Šaltinio kodas',
    'AboutTab.OpenGitHub': 'Atidaryti GitHub',
    'AboutTab.UniqueTech': 'Unikali technologija',
    'AboutTab.TechDescription': 'Naudojame unikalią technologiją blokavimams aplenkti, kuri užtikrina stabilų ryšį net esant apribojimams.',
    'ThemeVeryDark': 'Labai tamsi',
    'ThemeDuck': 'Antis',
    'ThemeGlass': 'Stiklas',
    'ThemeGlassGray': 'Pilkas stiklas',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Šią savaitę jums liko **%1$d** nemokamas transkribavimas.',
      few_value: 'Šią savaitę jums liko **%1$d** nemokami transkribavimai.',
      many_value: 'Šią savaitę jums liko **%1$d** nemokamų transkribavimų.',
      other_value: 'Šią savaitę jums liko **%1$d** nemokamų transkribavimų.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Šis balso pranešimas yra per ilgas, kad būtų transkribuotas.',
    'AudioAndVideoTranscription.FloodWait': 'Balso pranešimų transkribavimas šiuo metu nepasiekiamas. Bandykite dar kartą vėliau.',
    'Archive.Empty.Title': 'Archyvas tuščias',
    'Archive.Empty.Subtitle': 'Jūsų archyvuojami pokalbiai bus perkelti čia.',
    'GhostMode.Title': 'Nematomas režimas',
    'GhostMode.Subtitle': 'Paslepia jūsų internetinį statusą, paskutinio apsilankymo laiką ir skaitymo žymas. Skaitykite žinutes be pėdsako — niekas nesužinos, kad buvote čia.',
    'GhostMode.Warning': 'Žinutės siuntimas, skambutis ar reakcija jus išduos. Neskaičiuotų pranešimų skaitikliai gali grįžti po kitos sinchronizacijos.',
    'Proxy': 'Tarpinis serveris',
    'Proxy.Enabled': 'Naudoti tarpinį serverį',
    'Proxy.Type': 'Prisijungimo tipas',
    'Proxy.Type.MTProto': 'MTProto tarpinis serveris',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Pridėti tarpinį serverį',
    'Proxy.Add.Button': 'Pridėti',
    'Proxy.Import': 'Importuoti',
    'Proxy.ImportLink': 'Tarpinio serverio nuoroda (t.me/proxy?... arba tg://proxy?...)',
    'Proxy.Server': 'Serveris',
    'Proxy.Port': 'Prievadas',
    'Proxy.Secret': 'Paslaptis (nebūtina)',
    'Proxy.Username': 'Vartotojo vardas',
    'Proxy.Password': 'Slaptažodis',
    'Proxy.Servers': 'Išsaugoti tarpiniai serveriai',
    'Proxy.Browser.Note': 'Naršyklėje srautą gali nukreipti tik MTProto tarpinis serveris. SOCKS5 ir HTTP įrašai išsaugomi, bet ryšys lieka tiesioginis.'
  },
  'lv': {
    'PinnedChatsShort': 'Piespraustie',
    'FilterAllChatsShort': 'Visi',
    'AboutTab.Title': 'Par mums',
    'AboutTab.ProjectName': 'Projekta nosaukums',
    'AboutTab.Technology': 'Uz kā būvēts',
    'AboutTab.Version': 'Versija',
    'AboutTab.Status': 'Statuss',
    'AboutTab.StatusPlaceholder': 'Pagaidu aizstājējs',
    'AboutTab.SourceCode': 'Avota kods',
    'AboutTab.OpenGitHub': 'Atvērt GitHub',
    'AboutTab.UniqueTech': 'Unikāla tehnoloģija',
    'AboutTab.TechDescription': 'Mēs izmantojam unikālu tehnoloģiju, lai apietu bloķēšanu, kas nodrošina stabilu piekļuvi pat ierobežojumu apstākļos.',
    'ThemeVeryDark': 'Ļoti tumša',
    'ThemeDuck': 'Pīle',
    'ThemeGlass': 'Stikls',
    'ThemeGlassGray': 'Pelēks stikls',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Šonedēļ jums ir palicis **%1$d** bezmaksas transkribējums.',
      other_value: 'Šonedēļ jums ir palikuši **%1$d** bezmaksas transkribējumi.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'Šī balss ziņa ir pārāk gara, lai to transkribētu.',
    'AudioAndVideoTranscription.FloodWait': 'Balss ziņojumu transkripcija šobrīd nav pieejama. Lūdzu, mēģiniet vēlāk.',
    'Archive.Empty.Title': 'Arhīvs ir tukšs',
    'Archive.Empty.Subtitle': 'Jūsu arhivētās sarunas tiks pārvietotas šeit.',
    'GhostMode.Title': 'Neredzams režīms',
    'GhostMode.Subtitle': 'Slēpj jūsu tiešsaistes statusu, pēdējo apmeklējuma laiku un lasīšanas atzīmes. Lasiet ziņas bez pēdām — neviens neuzzinās, ka bijāt šeit.',
    'GhostMode.Warning': 'Ziņojuma nosūtīšana, zvans vai reakcija jūs atklās. Nenolasīto rādītāji pēc nākamās sinhronizācijas var atgriezties.',
    'Proxy': 'Starpniekserveris',
    'Proxy.Enabled': 'Izmantot starpniekserveri',
    'Proxy.Type': 'Savienojuma veids',
    'Proxy.Type.MTProto': 'MTProto starpniekserveris',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Pievienot starpniekserveri',
    'Proxy.Add.Button': 'Pievienot',
    'Proxy.Import': 'Importēt',
    'Proxy.ImportLink': 'Starpniekservera saite (t.me/proxy?... vai tg://proxy?...)',
    'Proxy.Server': 'Serveris',
    'Proxy.Port': 'Ports',
    'Proxy.Secret': 'Noslēpums (nav obligāti)',
    'Proxy.Username': 'Lietotājvārds',
    'Proxy.Password': 'Parole',
    'Proxy.Servers': 'Saglabātie starpniekserveri',
    'Proxy.Browser.Note': 'Pārlūkā trafiku var novirzīt tikai MTProto starpniekserveris. SOCKS5 un HTTP ieraksti tiek saglabāti, bet savienojums paliek tiešs.'
  },
  'et': {
    'PinnedChatsShort': 'Kinnitatud',
    'FilterAllChatsShort': 'Kõik',
    'AboutTab.Title': 'Meist',
    'AboutTab.ProjectName': 'Projekti nimi',
    'AboutTab.Technology': 'Millele ehitatud',
    'AboutTab.Version': 'Versioon',
    'AboutTab.Status': 'Olek',
    'AboutTab.StatusPlaceholder': 'Ajutine koht',
    'AboutTab.SourceCode': 'Lähtekood',
    'AboutTab.OpenGitHub': 'Ava GitHub',
    'AboutTab.UniqueTech': 'Ainulaadne tehnoloogia',
    'AboutTab.TechDescription': 'Kasutame ainulaadset tehnoloogiat blokeeringutest möödahiilimiseks, mis tagab stabiilse juurdepääsu ka piirangute tingimustes.',
    'ThemeVeryDark': 'Väga tume',
    'ThemeDuck': 'Part',
    'ThemeGlass': 'Klaas',
    'ThemeGlassGray': 'Hall klaas',
    'AudioAndVideoTranscription.TrialLeft': {
      one_value: 'Sel nädalal on teil jäänud **%1$d** tasuta transkribeerimine.',
      other_value: 'Sel nädalal on teil jäänud **%1$d** tasuta transkribeerimist.'
    },
    'AudioAndVideoTranscription.VoiceTooLong': 'See häälsõnum on transkribeerimiseks liiga pikk.',
    'AudioAndVideoTranscription.FloodWait': 'Häälsõnumite transkribeerimine pole praegu saadaval. Palun proovige hiljem uuesti.',
    'Archive.Empty.Title': 'Arhiiv on tühi',
    'Archive.Empty.Subtitle': 'Teie arhiveeritud vestlused teisaldatakse siia.',
    'GhostMode.Title': 'Nähtamatu režiim',
    'GhostMode.Subtitle': 'Peidab teie veebis oleku, viimase külastuse aja ja lugemismärked. Lugege sõnumeid jäljetult — keegi ei saa teada, et siin olite.',
    'GhostMode.Warning': 'Sõnumi saatmine, kõne või reaktsioon paljastab teid. Lugemata sõnumite loendurid võivad pärast järgmist sünkroonimist tagasi tulla.',
    'Proxy': 'Puhverserver',
    'Proxy.Enabled': 'Kasuta puhverserverit',
    'Proxy.Type': 'Ühenduse tüüp',
    'Proxy.Type.MTProto': 'MTProto puhverserver',
    'Proxy.Type.SOCKS5': 'SOCKS5',
    'Proxy.Type.HTTP': 'HTTP',
    'Proxy.Add': 'Lisa puhverserver',
    'Proxy.Add.Button': 'Lisa',
    'Proxy.Import': 'Impordi',
    'Proxy.ImportLink': 'Puhverserveri link (t.me/proxy?... või tg://proxy?...)',
    'Proxy.Server': 'Server',
    'Proxy.Port': 'Port',
    'Proxy.Secret': 'Saladus (valikuline)',
    'Proxy.Username': 'Kasutajanimi',
    'Proxy.Password': 'Parool',
    'Proxy.Servers': 'Salvestatud puhverserverid',
    'Proxy.Browser.Note': 'Brauseris saab liiklust suunata ainult MTProto puhverserver. SOCKS5 ja HTTP kirjed salvestatakse, kuid ühendus jääb otseseks.'
  }
};

export default langCustom;
